spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: 172.16.203.171
    username: guest
    password: guest
    connection-timeout: 15000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8764
env: 
        test